WhiteLagoon.Web/Controllers/AmenityController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WhiteLagoon.Application.Common.Interfaces;
using WhiteLagoon.Domain.Entities;
using WhiteLagoon.Web.ViewModels;

namespace WhiteLagoon.Web.Controllers
{

    public class AmenityController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;   //o nome _unitOfWork é o que quisermos

        //Estamos a aceder através do repositório
        public AmenityController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            var amenities = _unitOfWork.Amenity.GetAll(includeProperties: "Villa");
            return View(amenities);
        }

        //1 - CREATE
        //GET - Este é um clique normal que "mostra" o formulário
        public IActionResult Create()
        {
            AmenityVM amenityVM = new()
            {
                //Estamos a criar um dropdown (um select) mas mostra no Amenity os ids da Villa
                VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                }),
            };

            return View(amenityVM);
        }

        //POST - Aqui é para gravarmos os dados do formulário
        [HttpPost]  //este método vai receber pelo método post os dados do formulário
        [ValidateAntiForgeryToken]  //para segurança
        public IActionResult Create(AmenityVM obj) 
        {

            if (ModelState.IsValid)
            {

                _unitOfWork.Amenity.Add(obj.Amenity);           //para injectar na bd
                _unitOfWork.Save();                             //vai ver que alterações foram preparadas e faz save na bd

                TempData["success"] = "The Amenity has been created sucessfully!";
                return RedirectToAction(nameof(Index));
            }

            //Dropdown
            obj.VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString(),
            });
            TempData["error"] = "The Amenity could not be created!";
            return View(obj);
        }

        // 2 - EDIT
        //GET - este é para, depois de selecionar qual é aquele que quero editar, recebe o villanumberid
        public IActionResult Update(int amenityId)
        {
            AmenityVM amenityVM = new()
            {
                VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                Amenity = _unitOfWork.Amenity.Get(_ => _.Id == amenityId)
            };

            if (amenityVM.Amenity is null)
            {
                return RedirectToAction("Error", "Home");
            }

            return View(amenityVM);
        }

        //POST - para gravar os dados atualizados
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(AmenityVM amenityVM)  //metemos VillaNumberVM (porque é o modelo) e a var é o nome que quisermos: villaNumberVM no caso
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Amenity.Update(amenityVM.Amenity);    //para injectar na bd
                _unitOfWork.Save();                                     //vai ver que alterações foram preparadas e faz save na bd

                TempData["success"] = "The Amenity has been updated sucessfully!";
                return RedirectToAction(nameof(Index));
            }

            //Se erro, volta para trás e recarregamos o dropdown
            amenityVM.VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString(),
            });
            TempData["error"] = "The Amenity could not be updated!";

            return View(amenityVM);
        }

        // 3 - DELETE
        //GET - este é para, depois de selecionar qual é aquele que quero eliminar, recebe o villaNumberId
        public IActionResult Delete(int amenityId)
        {
            AmenityVM amenityVM = new()
            {
                VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                }),
                Amenity = _unitOfWork.Amenity.Get(_ => _.Id == amenityId)
            };

            if (amenityVM.Amenity is null)
            {
                return RedirectToAction("Error", "Home");
            }

            return View(amenityVM);
        }

        //POST - para gravar os dados atualizados depois de ele apagar
        [HttpPost]
        public IActionResult Delete(AmenityVM amenityVM)
        {
            Amenity? objFromDb = _unitOfWork.Amenity.Get(_ => _.Id == amenityVM.Amenity.Id);
            if (objFromDb is not null)
            {
                _unitOfWork.Amenity.Remove(objFromDb);
                _unitOfWork.Save();

                TempData["success"] = "The Amenity has been deleted successfully.";

                return RedirectToAction(nameof(Index));
            }

            TempData["error"] = "The Amenity could not be deleted.";
            return View(amenityVM);
        }
    }
}

WhiteLagoon.Web/Controllers/VillaController.cs
using Microsoft.AspNetCore.Mvc;
using WhiteLagoon.Application.Common.Interfaces;
using WhiteLagoon.Domain.Entities;

namespace WhiteLagoon.Web.Controllers
{

    public class VillaController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;   //o nome _unitOfWork é o que quisermos

        //para as imagens
        private readonly IWebHostEnvironment _webHostEnvironment;

        //CONSTRUTOR
        //Estamos a aceder através do repositório
        public VillaController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        //INDEX
        public IActionResult Index()
        {
            var villas = _unitOfWork.Villa.GetAll();

            return View(villas);
        }

        //1 - CREATE A NEW VILLA
        //GET - Este é um clique normal que "mostra" o formulário
        public IActionResult Create()
        {
            return View();
        }

        //POST - Aqui é para gravarmos os dados do formulário
        [HttpPost]  //este método vai receber pelo método post os dados do formulário
        [ValidateAntiForgeryToken]  //para segurança
        public IActionResult Create(Villa obj)  //metemos Villa (porque é o modelo) e a var é o nome que quisermos: obj no caso
        {
            //Validações personalizadas - que o modelo não prevê
            //Fazemos essas mesmo antes de ver se o modelo está válido ou não, ie, antes da linha 42
            if (obj.Name == obj.Description)
            {
                ModelState.AddModelError("Name", "The Description cannot be the same as the Name"); 
            }

            if (ModelState.IsValid)     //validações do lado do servidor
            {
                //File Upload
                if (obj.Image is not null)
                {
                    //Devemos gerar sempre nomes aleatórios na bd para que ela não estoire cada vez que o user faz upload de uma
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(obj.Image.FileName);
                    //Guid é o que garante o nome igual. Defini aqui o nome para a imagem
                    //Preciso também da extensão da imagem. Esse comando é o que esta a seguir ao +. 
                    //onde vou guardar a imagem?
                    string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, @"images\VillaImages");
                    //(vai dar ao caminho até à nossa pasta: www.root + o caminho para as pastas)

                    //proteção para a bd não estoirar
                    using (var fileStream = new FileStream(Path.Combine(imagePath, fileName), FileMode.Create))
                    {
                        obj.Image.CopyTo(fileStream);
                    }
                    obj.ImageUrl = @"\images\VillaImages\" + fileName;
                }
                else
                {
                    //Se o user não colocar imagem, é colocado esta por default
                    obj.ImageUrl = "https://placehold.co/600x400";
                }


                _unitOfWork.Villa.Add(obj);    //para injectar na bd
                _unitOfWork.Save();            //vai ver que alterações foram preparadas e faz save na bd

                TempData["success"] = "The Villa has been created sucessfully!";
                return RedirectToAction(nameof(Index));
            }

            TempData["error"] = "The Villa could not be created!";
            return View(obj);   
        }

        // 2 - EDIT
        //GET - este é para, depois de selecionar qual é aquele que quero editar, recebe o id 
        public IActionResult Update(int villaId)
        {
            //Aqui estou a aceder à bd, a comparar com o id que foi selecionado pelo clique do get
            Villa? obj = _unitOfWork.Villa.Get(x => x.Id == villaId);

            if (obj is null)
            {
                return RedirectToAction("Error", "Home");   //1º o ficheiro, depois a vista. É o error, da vista Home. Temos de indicar o caminho.
            }
            return View(obj);   //se não for nulo, devolvo TODOS os dados da Villa que quero abrir e editar
        }

        //POST - para gravar os dados atualizados
        [HttpPost]  
        [ValidateAntiForgeryToken]  
        public IActionResult Update(Villa obj)  //metemos Villa (porque é o modelo) e a var é o nome que quisermos: obj no caso
        { 
            if (ModelState.IsValid && obj.Id > 0)             //validações do lado do servidor
                                                              //segurança adicional - se o Id for zero, nunca dá update. Zero é para criar.
            {
				//File Upload
				if (obj.Image is not null)
				{
					string fileName = Guid.NewGuid().ToString() + Path.GetExtension(obj.Image.FileName);
					string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, @"images\VillaImages");
                        
                    //Se existir imagem, o objetivo é apagá-la antes de colocar a nova
                    if (!string.IsNullOrEmpty(obj.ImageUrl))
                    {
                        var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
                        //Para tirar catateres especiais do path, usamos o TrimStart.
                       
                        //Se o ficheiro existir, vamos apagar a imagem
                        if (System.IO.File.Exists(oldImagePath))
                            System.IO.File.Delete(oldImagePath);
					}
					//proteção para a bd não estoirar
					using (var fileStream = new FileStream(Path.Combine(imagePath, fileName), FileMode.Create))
					{
						obj.Image.CopyTo(fileStream);
					}
					obj.ImageUrl = @"\images\VillaImages\" + fileName;
				}

				_unitOfWork.Villa.Update(obj);         //para injectar na bd c/o update
                _unitOfWork.Save();                   //vai ver que alterações foram preparadas e faz save na bd

                TempData["success"] = "The Villa has been updated sucessfully!";
                return RedirectToAction(nameof(Index));
            }
            TempData["error"] = "The Villa could not be updated!";
            return View(obj);
        }

        // 3 - DELETE
        //GET - este é para, depois de selecionar qual é aquele que quero eliminar, recebe o id 
        public IActionResult Delete(int villaId)
        {
            //Aqui estou a aceder à bd, a comparar com o id que foi selecionado pelo clique do get
            Villa? obj = _unitOfWork.Villa.Get(x => x.Id == villaId); 

            if (obj == null)
            {
                return RedirectToAction("Error", "Home");   //1º o ficheiro, depois a vista. É o error, da vista Home. Temos de indicar o caminho.
            }

            return View(obj);   //se não for nulo, devolvo TODOS os dados da Villa que quero abrir e editar
        }

        //POST - para gravar os dados atualizados depois de ele apagar
        [HttpPost]
        public IActionResult Delete(Villa obj)  //metemos Villa (porque é o modelo) e a var é o nome que quisermos: obj no caso
        {
            Villa? objFromDb = _unitOfWork.Villa.Get(_ => _.Id == obj.Id);

            if (objFromDb is not null)
            {
				//Se existir imagem, o objetivo é apagá-la antes de colocar a nova
				if (!string.IsNullOrEmpty(objFromDb.ImageUrl))
				{
					var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, objFromDb.ImageUrl.TrimStart('\\'));
					//Para tirar catateres especiais do path, usamos o TrimStart.

					//Se o ficheiro existir, vamos apagar a imagem
					if (System.IO.File.Exists(oldImagePath))
						System.IO.File.Delete(oldImagePath);
				}
				_unitOfWork.Villa.Remove(objFromDb);
                _unitOfWork.Save();              //vai ver que alterações foram preparadas e faz save na bd

                TempData["success"] = "The Villa has been deleted sucessfully!";
                return RedirectToAction(nameof(Index));
            }

            TempData["error"] = "The Villa could not be deleted!";
            return View(obj);
        }
    }
}

WhiteLagoon.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WhiteLagoon.Web</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/css/bootstrap.min.css" integrity="sha512-jnSuA4Ss2PkkikSOLtYs8BlYIeeIK1h99ty4YfvRPAlzr377vr3CXDb7sb7eEEBYjDtcYj+AjBH3FLv5uSJuXg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WhiteLagoon.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" integrity="sha512-6S2HWzVFxruDlZxI3sXOZZ4/eJ8AcxkQH1+JjSe/ONCEqR9L4Ysq5JdT5ipqtzU7WHalNwzwBv+iE51gNHJNqQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/resort.png" style="width: 35px" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Content Management
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Villa" asp-action="Index">Villas</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="VillaNumber" asp-action="Index">Villa Numbers</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Amenity" asp-action="Index">Amenities</a></li>
                            </ul>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main">
            <!-- aqui chama o _Notification para aparecerem as boxes com o sucesso ou erro-->
            <partial name="_Notification" />
            
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-dark text-muted">
        <div class="container text-center">
           Made with <i class="bi bi-heart-fill"></i> by Ritans
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.bundle.min.js" integrity="sha512-7Pi/otdlbbCR+LnW+F7PwFcSDJOuUJB3OxtEHbg4vSMvzvJjde4Po1v4BR9Gdc9aXNUNFVUY+SK51wWT8WF0Gg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WhiteLagoon.Web/Views/Shared/_Notification.cshtml
@if (TempData["error"] != null)
{
    <!-- o toastr depende do jquery, por isso precisamos de meter o script do jquery em cada um destes ifs, para ele ler o script do toastr-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script type="text/javascript">
        toastr.options = {
            "positionClass": "toast-top-center",
            "progressBar": true,
            "closeButton": true,
        }
        toastr.error('@TempData["error"]');
    </script>

}

@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.options = {
            "positionClass": "toast-top-center",
            "progressBar": true,
            "closeButton": true,
        }
        toastr.success('@TempData["success"]');
    </script>
}

WhiteLagoon.Web/Views/Shared/_VillaDetail.cshtml
@model Villa

<div class="row">
	<div class="col-12 col-md-5">
		<img src="@Model.ImageUrl" style="border-radius:10px;" width="100%" />
	</div>
	<div class="col-12 col-md-7">
		<div class="row p-2">
			<div class="col-12">
				<p class="card-title text-warning" style="font-size:xx-large">@Model.Name</p>
				<p class="card-text" style="font-size:large">
					@Html.Raw(Model.Description)
				</p>
				@if (Model.VillaAmenity != null && Model.VillaAmenity.Count() > 0)
				{
					<p class="h5 text-white">Villa Amenities</p>
					<ul>
						@foreach (var amenity in Model.VillaAmenity)
						{
							<li>@amenity.Name</li>
						}
					</ul>
				}
			</div>
		</div>
		<div class="row col-12">
			<span class="text-end p-0 pt-3 m-0">
				<span class="float-right">Max Occupancy : @Model.Occupancy adults </span><br />
				<span class="float-right pt-1">Villa Size :  @Model.Sqft sqft</span><br />
				<p class="text-warning font-weight-bold pt-1">
					<span style=" #ff6a00">
						@Model.Price.ToString("c") / night
					</span>
				</p>
			</span>
		</div>
	</div>
</div>